spring:
  application:
    name: hr-worker
  server:
    port: 8001
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console